
DATA:
  ROOT: './data/SEN12MS'
  LABELS_PER_CLASS: 20
  NUM_CLASSES: 11
  PATCH_SIZE: 16

MODEL:
  PRETRAINED: './output/pretrain/pretrained.pth'
  FROZEN: True

OPTIM:
  LR: 0.001
  BETAS: [0.9, 0.999]
  EPOCHS: 10
  BATCH_SIZE: 32

OUTPUT_DIR: './output/finetune'
SEED: 42
